### ISSUE TITLE
Не хватает файлов

### ISSUE THREAD

**Issue by vztot** [madmis/kuna-bot#4]
Доброго времени суток! Я долго не могу решить эту проблему. 
![capture](https://user-images.githubusercontent.com/35550361/35078014-c891efea-fc08-11e7-8569-140b135648d7.JPG)
С подобной ошибкой как у меня уже тут отписывались. При вводе команд "$ cd ~/kuna-bot/app" и "$ composer install" у меня не создаётся файл "kuna-bot/app/bin/../vendor/autoload.php"
Извините за тупые вопросы если они таковые, но как мне быть? Нужно ли ставить Symfony"?

**Comment by madmis** [comment]
@vztot 
Если у вас не отрабатывает `composer install`, значит должна быть какая-то ошибка. 

Можете показать текст ошибки после выполнения команды `composer install`?

**Comment by vztot** [comment]
Да тут целый набор ошибок. Я и не заметил

> oleksandr@KunaBot4:~$ cd ~/kuna-bot/app
> oleksandr@KunaBot4:~/kuna-bot/app$ composer install
> Cannot create cache directory /home/oleksandr/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
> Cannot create cache directory /home/oleksandr/.composer/cache/files/, or directory is not writable. Proceeding without cache
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - This package requires php ^7.1.3 but your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 2
>     - The requested PHP extension ext-bcmath ^7.1 has the wrong version (7.0.22-0ubuntu0.16.04.1) installed. Install or enable PHP's bcmath extension.
>   Problem 3
>     - Installation request for doctrine/annotations 1.6.x-dev -> satisfiable by doctrine/annotations[1.6.x-dev].
>     - doctrine/annotations 1.6.x-dev requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 4
>     - Installation request for doctrine/annotations dev-master -> satisfiable by doctrine/annotations[dev-master].
>     - doctrine/annotations dev-master requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 5
>     - Installation request for doctrine/cache 1.8.x-dev -> satisfiable by doctrine/cache[1.8.x-dev].
>     - doctrine/cache 1.8.x-dev requires php ~7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 6
>     - Installation request for doctrine/cache dev-master -> satisfiable by doctrine/cache[dev-master].
>     - doctrine/cache dev-master requires php ~7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 7
>     - Installation request for madmis/exchange-api 0.1.3 -> satisfiable by madmis/exchange-api[0.1.3].
>     - madmis/exchange-api 0.1.3 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 8
>     - Installation request for madmis/kuna-api dev-master -> satisfiable by madmis/kuna-api[dev-master].
>     - madmis/kuna-api dev-master requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 9
>     - Installation request for symfony/cache 4.0.x-dev -> satisfiable by symfony/cache[4.0.x-dev].
>     - symfony/cache 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 10
>     - Installation request for symfony/cache dev-master -> satisfiable by symfony/cache[dev-master].
>     - symfony/cache dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 11
>     - Installation request for symfony/config 4.0.x-dev -> satisfiable by symfony/config[4.0.x-dev].
>     - symfony/config 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 12
>     - Installation request for symfony/config dev-master -> satisfiable by symfony/config[dev-master].
>     - symfony/config dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 13
>     - Installation request for symfony/console 4.0.x-dev -> satisfiable by symfony/console[4.0.x-dev].
>     - symfony/console 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 14
>     - Installation request for symfony/console dev-master -> satisfiable by symfony/console[dev-master].
>     - symfony/console dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 15
>     - Installation request for symfony/debug 4.0.x-dev -> satisfiable by symfony/debug[4.0.x-dev].
>     - symfony/debug 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 16
>     - Installation request for symfony/debug dev-master -> satisfiable by symfony/debug[dev-master].
>     - symfony/debug dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 17
>     - Installation request for symfony/dependency-injection 4.0.x-dev -> satisfiable by symfony/dependency-injection[4.0.x-dev].
>     - symfony/dependency-injection 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 18
>     - Installation request for symfony/dependency-injection dev-master -> satisfiable by symfony/dependency-injection[dev-master].
>     - symfony/dependency-injection dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 19
>     - Installation request for symfony/event-dispatcher 4.0.x-dev -> satisfiable by symfony/event-dispatcher[4.0.x-dev].
>     - symfony/event-dispatcher 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 20
>     - Installation request for symfony/event-dispatcher dev-master -> satisfiable by symfony/event-dispatcher[dev-master].
>     - symfony/event-dispatcher dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 21
>     - Installation request for symfony/filesystem 4.0.x-dev -> satisfiable by symfony/filesystem[4.0.x-dev].
>     - symfony/filesystem 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 22
>     - Installation request for symfony/filesystem dev-master -> satisfiable by symfony/filesystem[dev-master].
>     - symfony/filesystem dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 23
>     - Installation request for symfony/finder 4.0.x-dev -> satisfiable by symfony/finder[4.0.x-dev].
>     - symfony/finder 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 24
>     - Installation request for symfony/finder dev-master -> satisfiable by symfony/finder[dev-master].
>     - symfony/finder dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 25
>     - Installation request for symfony/flex 1.0.x-dev -> satisfiable by symfony/flex[1.0.x-dev].
>     - symfony/flex 1.0.x-dev requires composer-plugin-api ^1.1 -> no matching package found.
>   Problem 26
>     - Installation request for symfony/flex dev-master -> satisfiable by symfony/flex[dev-master].
>     - symfony/flex dev-master requires composer-plugin-api ^1.1 -> no matching package found.
>   Problem 27
>     - Installation request for symfony/framework-bundle 4.0.x-dev -> satisfiable by symfony/framework-bundle[4.0.x-dev].
>     - symfony/framework-bundle 4.0.x-dev requires ext-xml * -> the requested PHP extension xml is missing from your system.
>   Problem 28
>     - Installation request for symfony/framework-bundle dev-master -> satisfiable by symfony/framework-bundle[dev-master].
>     - symfony/framework-bundle dev-master requires ext-xml * -> the requested PHP extension xml is missing from your system.
>   Problem 29
>     - Installation request for symfony/http-foundation 4.0.x-dev -> satisfiable by symfony/http-foundation[4.0.x-dev].
>     - symfony/http-foundation 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 30
>     - Installation request for symfony/http-foundation dev-master -> satisfiable by symfony/http-foundation[dev-master].
>     - symfony/http-foundation dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 31
>     - Installation request for symfony/http-kernel 4.0.x-dev -> satisfiable by symfony/http-kernel[4.0.x-dev].
>     - symfony/http-kernel 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 32
>     - Installation request for symfony/http-kernel dev-master -> satisfiable by symfony/http-kernel[dev-master].
>     - symfony/http-kernel dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 33
>     - Installation request for symfony/inflector 4.0.x-dev -> satisfiable by symfony/inflector[4.0.x-dev].
>     - symfony/inflector 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 34
>     - Installation request for symfony/inflector dev-master -> satisfiable by symfony/inflector[dev-master].
>     - symfony/inflector dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 35
>     - Installation request for symfony/routing 4.0.x-dev -> satisfiable by symfony/routing[4.0.x-dev].
>     - symfony/routing 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 36
>     - Installation request for symfony/routing dev-master -> satisfiable by symfony/routing[dev-master].
>     - symfony/routing dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 37
>     - Installation request for symfony/var-dumper 4.0.x-dev -> satisfiable by symfony/var-dumper[4.0.x-dev].
>     - symfony/var-dumper 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 38
>     - Installation request for symfony/var-dumper dev-master -> satisfiable by symfony/var-dumper[dev-master].
>     - symfony/var-dumper dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 39
>     - Installation request for symfony/yaml 4.0.x-dev -> satisfiable by symfony/yaml[4.0.x-dev].
>     - symfony/yaml 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 40
>     - Installation request for symfony/yaml dev-master -> satisfiable by symfony/yaml[dev-master].
>     - symfony/yaml dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 41
>     - Installation request for symfony/dotenv 4.0.x-dev -> satisfiable by symfony/dotenv[4.0.x-dev].
>     - symfony/dotenv 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 42
>     - Installation request for symfony/dotenv dev-master -> satisfiable by symfony/dotenv[dev-master].
>     - symfony/dotenv dev-master requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 43
>     - symfony/inflector 4.0.x-dev requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
>     - symfony/property-access 3.4.x-dev requires symfony/inflector ~3.1|~4.0 -> satisfiable by symfony/inflector[4.0.x-dev].
>     - Installation request for symfony/property-access 3.4.x-dev -> satisfiable by symfony/property-access[3.4.x-dev].
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
>   To enable extensions, verify that they are enabled in those .ini files:
>     - /etc/php/7.0/cli/php.ini
>     - /etc/php/7.0/cli/conf.d/10-opcache.ini
>     - /etc/php/7.0/cli/conf.d/10-pdo.ini
>     - /etc/php/7.0/cli/conf.d/20-bcmath.ini
>     - /etc/php/7.0/cli/conf.d/20-calendar.ini
>     - /etc/php/7.0/cli/conf.d/20-ctype.ini
>     - /etc/php/7.0/cli/conf.d/20-exif.ini
>     - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
>     - /etc/php/7.0/cli/conf.d/20-ftp.ini
>     - /etc/php/7.0/cli/conf.d/20-gettext.ini
>     - /etc/php/7.0/cli/conf.d/20-iconv.ini
>     - /etc/php/7.0/cli/conf.d/20-json.ini
>     - /etc/php/7.0/cli/conf.d/20-phar.ini
>     - /etc/php/7.0/cli/conf.d/20-posix.ini
>     - /etc/php/7.0/cli/conf.d/20-readline.ini
>     - /etc/php/7.0/cli/conf.d/20-shmop.ini
>     - /etc/php/7.0/cli/conf.d/20-sockets.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
>     - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
>   You can also run 'php --ini' inside terminal to see which files are used by PHP in CLI mode.

**Comment by madmis** [comment]
Ну во первых, у вас директория `/home/oleksandr/.composer/cache/files/` не доступна для записи.

А во вторых, [вот здесь](https://github.com/madmis/kuna-bot#run-on-the-local-machine) описаны требования для запуска бота. Ваша версия php не соответствует минимально требуемой. Обновляйте версию php и все будет гуд. 
Ну и обращайте больше внимания на ошибки в терминале. Там все ошибки видны и должны быть понятны.

**Comment by vztot** [comment]
Фух запустил... Теперь уже легче, но я подозреваю эти ошибки из-за настроек в конфиге
![capture2](https://user-images.githubusercontent.com/35550361/35119212-e50eff8e-fc9c-11e7-875d-03574d827ce9.JPG)

**Comment by vztot** [comment]
Случайно закрыл

**Comment by vztot** [comment]
```
# Trading pair
pair: btcuah
```
Тут можно поставить, например, ethuah?

```
# Trading pair configuration
base_currency:
    # If current value more than base currency account balance
    # account balance will be divided to a margin (below) count
    # result amount will be - order value
    boundary: 0.05
    # orders count and margin for each of them
    margin: [0.0001, 0.001]
quote_currency:
    # If current value more than quote currency account balance
    # account balance will be divided to a margin (below) count
    # result amount will be - order value
    boundary: 400
    # orders count and margin for each of them
    margin: [50, -50, -150]
```
Вот тут я вообще не понял (не силен в англ) ;) 
Вы  бы не могли объяснить алгоритм на пальцах?)

**Comment by madmis** [comment]
> Тут можно поставить, например, ethuah?

Да. Тут выставляется пара в соответствии той, которую вы видите в адресной строке браузера на куне: ethuah, wavesuah, bchbtc ...

base/quote - на паре btcuah: btc - базовая (base), uah - котируемая (quote) валюта

`boundary` - это сумма баланса для одного ордера. 
`margin` - это "сумма вашего заработка". 

Бот работает следующим образом: 
**Базовая валюта**

- Смотрит ваш баланс в базовой валюте. Если он больше `boundary` то делит ваш баланс на количество ордеров и получает итоговую сумму одного ордера. Иначе - ваш баланс и есть сумма ордера.
- Берет первую заявку в стакане на продажу - это будет стартовая цена на продажу. Проходит по каждому `margin` и к стартовой цене на продажу добавляет этот `margin`. В итоге получается цена, по которой выставляется ордер.

**Котируемая валюта**
Работает почти также, только смотрит в стакан покупки.

**Пример**
```
pair: btcuah
base_currency:
    boundary: 0.05
    margin: [200, 500]
quote_currency:
   boundary: 400
   margin: [50, -50, -150]
```
Допустим у нас на балансе 0.12 BTC. Топ цены в стаканах: продажа - 10000, покупка - 5000.

Начинает работать бот.  
0.12 / count(base_currency.margin) = 0.06. У нас будет 2 ордера объемом по 0.06 BTC
Далее берем топ цену на продажу и вычисляем цену для каждого ордера:
1. 10000 + base_currency.margin[1] = 10200 - цена первого ордера
2. 10000 + base_currency.margin[2] = 10500 - цена второго ордера
Ордера выставляются на биржу и сидим ждем, либо отменяем ордера вручную (бот автоматически только выставляет ордера).

Затем, когда у нас появляется котируемая валюта (сработал ордере на продажу или просто пополнили счет и, к примеру, у нас на балансе 20000 UAH ), бот выполняет:
20000 / count(quote_currency.margin) = 6666. У нас будет 3 ордера объемом по 6666 UAH
Далее берем топ цену на покупку и вычисляем цену для каждого ордера:
1. 5000 + quote_currency.margin[1] = 5050 - цена первого ордера
2. 5000 + quote_currency.margin[2] = 4950 - цена второго ордера
3. 5000 + quote_currency.margin[3] = 4850 - цена третьего ордера

И опять же ждем, пока ордера выполнятся, либо отменяем их вручную.

**Comment by vztot** [comment]
Спасибо за развернутый ответ. Будем разбираться)
