### ISSUE TITLE
Настройка пары eth/uah

### ISSUE THREAD

**Issue by shmaliy** [madmis/kuna-bot#5]
Возникли трудности с настройкой этой пары. Гривневого баланса хватит на 0,05 eth, но система упорно пытается купить 7.22. Где я могу ошибаться?

**Comment by madmis** [comment]
покажите логи бота.  И свой конфиг. 
API ключи только не показывайте.

**Comment by shmaliy** [comment]
# Trading pair
pair: ethuah

# Trading pair configuration
base_currency:
    # If current value more than base currency account balance
    # account balance will be divided to a margin (below) count
    # result amount will be - order value
    boundary: 1
    # orders count and margin for each of them
    margin: [1]
quote_currency:
    # If current value more than quote currency account balance
    # account balance will be divided to a margin (below) count
    # result amount will be - order value
    boundary: 400
    # orders count and margin for each of them
    margin: [50, -50, -150]

# Minimum amount for each currency to run tradings.
# if currency account balance less than this value, orders is not created
min_amounts:
   eth: 0.04
   uah: 1700

# Bot iteration timeout - seconds
iteration_timeout: 10

# debug info. Show bot memory usage
show_memory_usage: true

***************eth/uah***************
Check base currency (eth) balance
Available funds: 0.00000072 eth.
Base funds (eth) processing
	Boundary: 0.05
	Orders count: 2
	Margin: 2, 3
Account balance less than boundary, so only 1 order can be opened
Create orders configurations:
Order #1: volume|7.225E-7 price|34352.000000
Create eth SELL orders
Client error: `POST https://kuna.io/api/v2/orders` resulted in a `400 Bad Request` response:
{"error":{"code":2002,"message":"Failed to create order."}}

{"error":{"code":2002,"message":"Failed to create order."}}
Memory usage: 6144 Kb (6 Mb)

**Comment by shmaliy** [comment]
И еще вопрос:
Бот самообучаемый? (сделал 2 ордера и немного денег проиграл пока).
 Или я все же не понял как ему конфигурировать стратегию?

**Comment by madmis** [comment]
В общем баг есть (не учитывается мин. сумма для торгов), пофикшу как можно скорее.

Бот не самообучаемый. Стратегия очень простая. Подробно описана здесь - https://github.com/madmis/kuna-bot/issues/4#issuecomment-358873265
Бот по сути просто автоматизирует некие ручные операции.
